### ISSUE TITLE
Add a helper method for British English

### ISSUE THREAD

**Issue by chgasparoto** [chgasparoto/aws-polly-voices#3]
See #1 on how to implement it. It's very simple and it's the perfect candidate for the first issue collaboration.

Feel free to post any questions.

Code example: https://github.com/chgasparoto/aws-polly-voices/pull/2/files

**Comment by abraaoduarte** [comment]
I will implement this feature

**Comment by abraaoduarte** [comment]
### Adding British language #9

**Comment by chgasparoto** [comment]
Fixed by #9
