### ISSUE TITLE
Add a helper method for Icelandic Language

### ISSUE THREAD

**Issue by chgasparoto** [chgasparoto/aws-polly-voices#36]
See #1 on how to implement it. It's very simple and it's the perfect candidate for the first issue collaboration.

Feel free to post any questions.

Code example: https://github.com/chgasparoto/aws-polly-voices/pull/2/files

**Comment by merelyAnna** [comment]
Hey, I'd like to implement this. Can you assign this to me, please?

**Comment by merelyAnna** [comment]
#52

**Comment by merelyAnna** [comment]
I created a pull request ( #52 ). How do I properly link it to this issue?
