### ISSUE TITLE
Add a helper method for Indian English

### ISSUE THREAD

**Issue by chgasparoto** [chgasparoto/aws-polly-voices#38]
See #1 on how to implement it. It's very simple and it's the perfect candidate for the first issue collaboration.

Feel free to post any questions.

Code example: https://github.com/chgasparoto/aws-polly-voices/pull/2/files

**Comment by yashguptaz** [comment]
I am ready to take this issue, just one question, how do I get the mock voice names?
```{
  Gender: 'Male',
  Name: 'Giorgio',
  LanguageName: 'Italian',
  Id: 'Giorgio',
  LanguageCode: 'it-IT'
},```

**Comment by chgasparoto** [comment]
@yashguptaz you can extract from the [voices.json](https://github.com/chgasparoto/aws-polly-voices/blob/master/src/voices.json) file.

**Comment by yashguptaz** [comment]
You can review my PR now here,
https://github.com/chgasparoto/aws-polly-voices/pull/45#issue-325017293
