### ISSUE TITLE
Add a helper method for Canadian French

### ISSUE THREAD

**Issue by chgasparoto** [chgasparoto/aws-polly-voices#39]
See #1 on how to implement it. It's very simple and it's the perfect candidate for the first issue collaboration.

Feel free to post any questions.

Code example: https://github.com/chgasparoto/aws-polly-voices/pull/2/files

**Comment by Babadzhanov** [comment]
Hi, I'd like to implement this.

**Comment by Babadzhanov** [comment]
#56

**Comment by Babadzhanov** [comment]
chgasparoto/aws-polly-voices#56

**Comment by Babadzhanov** [comment]
resolve #56
