### ISSUE TITLE
Add a helper method for Arabic Language

### ISSUE THREAD

**Issue by chgasparoto** [chgasparoto/aws-polly-voices#6]
See #1 on how to implement it. It's very simple and it's the perfect candidate for the first issue collaboration.

Feel free to post any questions.

Code example: https://github.com/chgasparoto/aws-polly-voices/pull/2/files

**Comment by bigblackclock** [comment]
i can do this

**Comment by chgasparoto** [comment]
@bigblackclock are you still interested in implement it?

**Comment by bigblackclock** [comment]
@chgasparoto i already  finished it

**Comment by chgasparoto** [comment]
it didn't get merged
