### ISSUE TITLE
Add a helper method for Swedish Language

### ISSUE THREAD

**Issue by chgasparoto** [chgasparoto/aws-polly-voices#7]
See #1 on how to implement it. It's very simple and it's the perfect candidate for the first issue collaboration.

Feel free to post any questions.

Code example: https://github.com/chgasparoto/aws-polly-voices/pull/2/files

**Comment by mcrosby114** [comment]
I'll take this one if available!

**Comment by chgasparoto** [comment]
@mcrosby114 are you still interested in implement it?

**Comment by mcrosby114** [comment]
https://github.com/chgasparoto/aws-polly-voices/issues/7#issuecomment-538721779 Yes I'll get that in today

**Comment by chgasparoto** [comment]
closed by #65
